// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For migrations, use the direct connection (bypasses PgBouncer pooler)
    // At runtime, PrismaService uses DATABASE_URL (pooler) via the adapter in prisma.service.ts
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
